config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "**/Dockerfile*"
    - "Jenkinsfile"
    - "**/*.md"
    - "**/*.py"
    - "**/*.txt"
    - "**/*.sh"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.xml"